### ISSUE TITLE
请求开通 Discussion ，用该载体细分 Issue 种类

### ISSUE THREAD

**Issue by rijieli** [flaneur2020/pua-lang#20]
开通路径为 Repo 设置，然后在 Discussions 打勾。

利用该抓手，充分赋能 Github 讨论，及时有效分流无关语言与平台的讨论。

得益于 Discussion 支持创建多维问题深度组合拳(i.e. Category)，用细粒度的讨论，让方法论真正落地，实现价值转化。

**Comment by flaneur2020** [comment]
已开启 qwq https://github.com/flaneur2020/pua-lang/discussions
