### ISSUE TITLE
添加网页版

### ISSUE THREAD

**Issue by suulnnka** [flaneur2020/pua-lang#25]
原版是带有web online解释器的,只要开个gh-pages分支,make web_deploy一下,在github中启用一下gh-pages功能就可以生成网页版.

我这边只有windows环境,不太方便编译,就不提pull request的.

**Comment by Artoria2e5** [comment]
我试试吧，正好还有一堆内置例子该改改。虽然我也是 Windows (

**Comment by Artoria2e5** [comment]
运行 `(cd web; yarn publish)` 就进 gh-pages 分支了。@flaneur2020 你去 repo 设置里面改一下？

**Comment by flaneur2020** [comment]
加了一把 👏 👏 👏  https://flaneur2020.github.io/pua-lang/
