### ISSUE TITLE
建议增加价值观检查

### ISSUE THREAD

**Issue by saltfishh** [flaneur2020/pua-lang#3]
根据代码风格和代码需求来判断代码撰写者的价值观.
如果其价值观不符合阿巴阿巴的价值观就拒绝为其编译/运行.
如此一来,底层逻辑清晰,上层设计明了,才能形成商业闭环,反哺供应链

**Comment by niejunhao** [comment]
不是我吹，我来写，CI都过不了

**Comment by codgician** [comment]
希望价值观考核有一天真的可以取消，不是说到那一天价值观不存在了，而是已经渗透到每一个阿里人血脉之中，那是一种大音希声、大象无形、大道无言的愿景。(doge)

**Comment by ICEYSELF** [comment]
> 不是我吹，我来写，CI都过不了

年会没你我不看

**Comment by Artoria2e5** [comment]
INTERCAL 语言里面确实有“态度检查”的设定，要求 PLEASE 不多不少。至于放进 pua……我暂时没什么想法。
