### ISSUE TITLE
建议用 闭环 作为循环关键词

### ISSUE THREAD

**Issue by Gaojianli** [flaneur2020/pua-lang#44]
闭环 代表 for ，打破 代表 break
```
闭环（赋能 i=0;i<=n;i++){
 打破
}
```

**Comment by nobodxbodon** [comment]
https://github.com/flaneur2020/pua-lang/pull/47 里好像是 闭环 表示 while。
个人感觉 闭环 的含义更接近 loop。while 有“每当”的含义，而且 闭环 更像名词而非连词。
BTW [木兰语言](https://gitee.com/MulanRevive/mulan-rework)是同时[支持 loop](https://gitee.com/MulanRevive/mulan-rework/blob/master/%E6%B5%8B%E8%AF%95/%E6%B5%81%E7%A8%8B%E6%8E%A7%E5%88%B6/%E5%BE%AA%E7%8E%AFloop.ul) 和 while：
```javascript
i = 0
loop {
    i += 1
    print(i)
    if i == 3 {
        break
    }
}
```

**Comment by flaneur2020** [comment]
> 个人感觉 闭环 的含义更接近 loop。

赞同，有没有关于 while 的关键词建议呢？

之前想法是在有限的关键词里把最经典的几个关键词（比如闭环 抓手）给用起来 🤔

```
闭环 (三七五) {
  输出("打通心智");
  破圈;
}
```

**Comment by nobodxbodon** [comment]
对行话不大熟，[这里](https://github.com/shadowings-zy/internet-industry-terms-generator) 似乎没看到特别恰当的。 又看了 [这里](https://zhuanlan.zhihu.com/p/70495913)，只看到“专注”也许有点接近？

**Comment by flaneur2020** [comment]
出于「最常用的语法」匹配「最经典的关键词」的考虑，我们暂时先用 while 作为闭环？qwq

**Comment by nobodxbodon** [comment]
@flaneur2020 没问题。万一真要往实用化走的时候再调整不迟 :D
