### ISSUE TITLE
一个中文的编程README.md放啥英文呢

### ISSUE THREAD

**Issue by kerncoola** [flaneur2020/pua-lang#51]
RT

**Comment by andelf** [comment]
一个中国人上啥github呢, gitee不香么

**Comment by NinthCode** [comment]
up

**Comment by hioop** [comment]
这就是另外一个问题了，
内卷，卷那些英文不好的[手动狗头]

**Comment by fuheihei** [comment]
坐稳了，要开始上升高度了，请速度与作者统一意识形态

**Comment by nobodxbodon** [comment]
也许，可以走 hybrid 风？参考 [字节跳动九周年张一鸣演讲全文](https://www.sohu.com/a/458331469_351788)：

> 关于如何面对失误，我有个“四部曲”。前三句话是从一本书摘出来的，是说当你遇到一个问题的时候，你有几件事情要做。第一步是realize it ，真实认识到错误，之后你就可以少懊恼一点了，认识到就是一种收获。你还可以correct it，改正它、修正它，这又是一种收获。你还可以learn from it，从这个错误中学习到背后的原因。书里面提了这三个步骤，后来我又加了一个：forgive it——如果你已经完成了前三步，那么你应该放下它。面对错误，很多人强调痛定思痛，我是建议：不要过长时间进入到自我指责的状态中。

**Comment by Artoria2e5** [comment]
本来就是照抄的懒得重写。
