### ISSUE TITLE
赋能之后的变量没法在右表达式使用

### ISSUE THREAD

**Issue by EchoZhaoH** [flaneur2020/pua-lang#59]
![image](https://user-images.githubusercontent.com/23427655/144192022-b71385d7-00ab-4d4f-b021-031ea55c8783.png)

**Comment by flaneur2020** [comment]
currently pua-lang do not support mutating variable yet, what we might try instead is:

```
赋能 福娃 = 福娃 联动 "xxx";
```

have to repeat `赋能` again yet >.<

**Comment by EchoZhaoH** [comment]
好吧，希望你们能早日支持 for 😂
